services:
  - type: web
    name: campanha-antiphishing-ads-ifsp
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_DOC_ID
        value: 1vh1kREco2S27GkhuoFww9alkrro05e1StFQiBu2FXKo
      - key: GOOGLE_SERVICE_ACCOUNT_B64
        sync: false
